// Reads the bundled layouts and wordlists and emits extension/lib/data.js
// with precomputed character-trigram counts per language. Run from repo root:
//
//   node extension/lib/build-models.mjs
//
// The generated file is committed; this script only re-runs when wordlists or
// layouts change.

import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const EXT_ROOT = path.resolve(__dirname, "..");
const LAYOUTS_DIR = path.join(EXT_ROOT, "data", "layouts");
const WORDLISTS_DIR = path.join(EXT_ROOT, "data", "wordlists");
const OUT_FILE = path.join(__dirname, "data.js");

const LETTER = /\p{L}/u;

function isLetter(ch) { return LETTER.test(ch); }

function alphabetOf(layout) {
  const out = new Set();
  for (const c of layout.normal) if (isLetter(c)) out.add(c.toLowerCase());
  for (const c of layout.shift) if (isLetter(c)) out.add(c.toLowerCase());
  return [...out].sort().join("");
}

function readWords(file) {
  if (!fs.existsSync(file)) return [];
  return fs.readFileSync(file, "utf8")
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && !s.startsWith("#"));
}

function trigramsFor(words) {
  const counts = new Map();
  let total = 0;
  for (const raw of words) {
    const word = raw.toLowerCase();
    if (!word) continue;
    const padded = "  " + word + " ";
    for (let i = 0; i + 3 <= padded.length; i++) {
      const tri = padded.substring(i, i + 3);
      counts.set(tri, (counts.get(tri) ?? 0) + 1);
      total++;
    }
  }
  return { counts: Object.fromEntries(counts), total };
}

function loadLayouts() {
  const out = {};
  for (const f of fs.readdirSync(LAYOUTS_DIR)) {
    if (!f.endsWith(".json")) continue;
    const json = JSON.parse(fs.readFileSync(path.join(LAYOUTS_DIR, f), "utf8"));
    out[json.id] = {
      id: json.id,
      name: json.name,
      language: json.language,
      normal: json.normal,
      shift: json.shift,
    };
  }
  return out;
}

function build() {
  const layouts = loadLayouts();
  const languages = {};

  for (const id of Object.keys(layouts).sort()) {
    const layout = layouts[id];
    const alphabet = alphabetOf(layout);
    const words = readWords(path.join(WORDLISTS_DIR, `${id}.txt`));
    const { counts, total } = trigramsFor(words);
    languages[id] = { layout, alphabet, total, counts };
  }

  const stats = Object.entries(languages)
    .map(([id, m]) => `${id}=${Object.keys(m.counts).length}t/${m.total}`)
    .join(" ");

  // Generated as ESM; large but compresses well.
  const banner = [
    "// AUTO-GENERATED by extension/lib/build-models.mjs",
    "// Source: extension/data/{layouts,wordlists}/",
    "// Do not edit by hand. Regenerate with: node extension/lib/build-models.mjs",
    `// Stats: ${stats}`,
    "",
  ].join("\n");

  const body = `export const LANGUAGES = ${JSON.stringify(languages, null, 0)};\n`;

  fs.writeFileSync(OUT_FILE, banner + body, "utf8");
  console.log(`wrote ${OUT_FILE}`);
  console.log(stats);
  console.log(`size: ${(fs.statSync(OUT_FILE).size / 1024).toFixed(1)} KB`);
}

build();
